apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out ./k8s-kompose
    kompose.version: 1.27.0 (b0ed6a2c9)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out ./k8s-kompose
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - name: web
          image: base-web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
#           resources: {}
#           volumeMounts:
#             - mountPath: /code
#               name: web-claim0
#       restartPolicy: Always
#       volumes:
#         - name: web-claim0
#           persistentVolumeClaim:
#             claimName: web-claim0
# status: {}
